<?php
/**
 * This file is generated by bin/translate.js
 * Do not edit this file manually.
 */

return array(
	'Loading Data'          => __( 'Loading Data', 'bstr_lang' ),
	'Boost'                 => __( 'Boost', 'bstr_lang' ),
	'min.'                  => __( 'min.', 'bstr_lang' ),
	'max.'                  => __( 'max.', 'bstr_lang' ),
	'Boosting'              => __( 'Boosting', 'bstr_lang' ),
	'Replace'               => __( 'Replace', 'bstr_lang' ),
	'Set'                   => __( 'Set', 'bstr_lang' ),
	'on all existing posts' => __( 'on all existing posts', 'bstr_lang' ),
	'between'               => __( 'between', 'bstr_lang' ),
	'and'                   => __( 'and', 'bstr_lang' ),
	'or'                    => __( 'or', 'bstr_lang' ),
	'Add'                   => __( 'Add', 'bstr_lang' ),
	'Add between'           => __( 'Add between', 'bstr_lang' ),
	'Boost Existing Posts'  => __( 'Boost Existing Posts', 'bstr_lang' ),
	'on new posts'          => __( 'on new posts', 'bstr_lang' ),
	'Boost New Posts?'      => __( 'Boost New Posts?', 'bstr_lang' ),
	'Yes'                   => __( 'Yes', 'bstr_lang' ),
	'No'                    => __( 'No', 'bstr_lang' ),
	'Saving options'        => __( 'Saving options', 'bstr_lang' ),
	'Options saved'         => __( 'Options saved', 'bstr_lang' ),
	'Save options'          => __( 'Save options', 'bstr_lang' ),
);
